# Author: Andreas Rupp, LUT University, 2022.
# Copied from: https://github.com/HyperHDG/HyperHDG/blob/main/.github/workflows/clang_format.yml

name: Clang

on: [push]

jobs:
  formatting-check:
    name: Test clang-format to change nothing
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Conduct Clang-Format Test
      uses: HyperHDG/actions@clang-format
      with:
        format_files: STAR.hxx STAR.cxx STAR.cxx.in
