# Author: Andreas Rupp, LUT University, 2022.
# Copied from: https://github.com/HyperHDG/HyperHDG/blob/main/.github/workflows/cmake.yml

name: CMake

on: [push]


jobs:
  # =============== Test code on Ubuntu 22.04 with all currently available compilers ===============
  build_and_test_ubuntu_22-04:
    strategy:
      matrix:
        osys: [ ubuntu-22.04 ]
        comp: [ {cxx: clang++-12}, {cxx: clang++-13}, {cxx: clang++-14},
                {cxx: g++-10}, {cxx: g++-11}, {cxx: g++-12} ]

    name: Test code with ${{ matrix.comp.cxx }} on ${{ matrix.osys }}
    runs-on: ${{ matrix.osys }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
       submodules: recursive
    - name: CXX compiler
      run: |
        sudo apt-get update;
        sudo apt-get install -y ${{ matrix.comp.cxx }}
    - name: Conduct cmake test
      uses: HyperHDG/actions@cmake
      with:
        cxx_compiler: ${{ matrix.comp.cxx }}
